[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52832_xxAA --allow-erase-all"

[build]
target = "thumbv7em-none-eabihf"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x"
]

[env]
DEFMT_LOG = "info"
BINDGEN_EXTRA_CLANG_ARGS = "-I/usr/include -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/lib/gcc/x86_64-linux-gnu/11/include"